Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -20,9 +20,19 @@ steps:
   args:
   - '-c'
   - |
-      echo "***********************"
-      echo "${BRANCH_NAME}"
-      echo "***********************"
+      if [ -f "tfbackend/${BRANCH_NAME}.tfbackend"] && -f "tfvars/${BRANCH_NAME}.tfvars"]; then
+        echo "***********************"
+        echo "${BRANCH_NAME}"
+        echo "***********************"
+      else
+        if [ ! -f "tfbackend/${BRANCH_NAME}.tfbackend"]; then
+          echo "Missing file 'tfbackend/${BRANCH_NAME}.tfbackend'
+        fi
+        if [ ! -f "tfvars/${BRANCH_NAME}.tfvars"]; then
+          echo "Missing file 'tfvars/${BRANCH_NAME}.tfvars'
+        fi
+      fi
+        exit 1
 
 # [START tf-init]
 - id: 'tf init'
@@ -47,11 +57,7 @@ steps:
           terraform init || exit 1
           cd ../../
         done
-<<<<<<< HEAD
-      fi
-=======
       fi 
->>>>>>> ed88843 (adding custom rules logic)
 # [END tf-init]
 
 # [START tf-plan]
@@ -66,31 +72,18 @@ steps:
         terraform plan
       else
         for dir in environments/*/
-<<<<<<< HEAD
-        do
-          cd ${dir}
-          env=${dir%*/}
-          env=${env#*/}
-          echo ""
-          echo "*************** TERRAFORM PLAN ******************"
-=======
         do 
           cd ${dir}   
           env=${dir%*/}
           env=${env#*/}  
           echo ""
           echo "*************** TERRAFOM PLAN ******************"
->>>>>>> ed88843 (adding custom rules logic)
           echo "******* At environment: ${env} ********"
           echo "*************************************************"
           terraform plan || exit 1
           cd ../../
         done
-<<<<<<< HEAD
-      fi
-=======
       fi 
->>>>>>> ed88843 (adding custom rules logic)
 # [END tf-plan]
 
 # [START tf-apply]
@@ -101,13 +94,8 @@ steps:
   - '-c'
   - |
       if [ -d "environments/$BRANCH_NAME/" ]; then
-<<<<<<< HEAD
-        cd environments/$BRANCH_NAME
-        terraform apply -auto-approve
-=======
         cd environments/$BRANCH_NAME  
         terraform apply -auto-approve"
->>>>>>> ed88843 (adding custom rules logic)
       else
         echo "***************************** SKIPPING APPLYING *******************************"
         echo "Branch '$BRANCH_NAME' does not represent an official environment."
